# kmeans clustering
assign 10 clusters based on ADT-antibody surface marker expression

In [63]:
import os, sys
import numpy as np
import pandas as pd


In [64]:
os.listdir("./filtered")

['CBMC_ADT_clr_filtered.csv', 'CBMC_ADT_filtered.csv', 'CBMC_rna_filtered.csv']

In [65]:
data_adtclr = pd.read_csv("./filtered/CBMC_ADT_clr_filtered.csv")

In [66]:
data_adtclr

Unnamed: 0  TACAGTGTCTCGGACG  GTTTCTACATCATCCC  ATCATGGAGTAGGCCA  \
0         CD3          0.003523         -0.178264         -1.647524   
1         CD4         -0.240099         -0.642570         -0.121233   
2         CD8         -0.052047          0.004057          1.601617   
3      CD45RA          1.826327          1.700110          3.972828   
4        CD56         -0.311558         -0.789173         -0.237918   
5        CD16          0.199267         -0.070051          0.873991   
6        CD10          0.130275          0.158208         -1.666572   
7       CD11c         -0.349298         -0.900399          1.448773   
8        CD14          0.199267          0.326831          0.826315   
9        CD19         -0.388519         -0.401408         -0.667032   
10       CD34         -0.388519          1.708805         -1.516354   
11       CCR5         -0.240099         -0.514737         -0.783804   
12       CCR7         -0.388519         -0.401408         -2.083087   

    GTACGTATCCCATTTA  ATGTGTGGTCGCCATG  AACGTTGTCAGTTAGC  CAGAATCGTACATCCA  \
0          -0.092524         -0.381939         -0.633771         -0.456502   
1          -0.340985         -0.564260         -0.473428         -0.574285   
2          -0.034255         -0.094257         -0.008065         -0.616845   
3           1.702563          1.751570          1.637907          1.769122   
4          -0.112727         -0.354540         -0.335278         -0.255831   
5          -0.053303          0.128887          0.037397          0.217953   
6          -0.112727          0.465359          0.273786          0.273013   
7          -0.266877         -0.354540         -0.105703         -0.038767   
8           0.495263          0.465359          0.059376          0.406544   
9          -0.603349         -0.787404         -0.511169         -0.318352   
10          0.055896          0.041875          0.101936          0.198905   
11         -0.243347         -0.301896         -0.185746         -0.318352   
12         -0.393629         -0.014214          0.142758         -0.286603   

    TCGGGACTCTGGCGTG  TGACTAGAGGATCGCA        ...         ATCGAGTTCAAGGTAA  \
0           0.090729         -0.024408        ...                -1.126395   
1          -0.399894          0.240641        ...                -0.404260   
2          -0.274731          0.119091        ...                -0.404260   
3           1.951481          4.243099        ...                 2.029353   
4          -0.582216         -0.134230        ...                 0.083443   
5           0.070110          0.484370        ...                 0.199275   
6          -0.163505         -1.558338        ...                 0.245085   
7           0.110932          0.815188        ...                -0.868566   
8           0.433015          0.703919        ...                 0.083443   
9          -0.756569         -0.418430        ...                -0.592312   
10         -0.335355         -1.693565        ...                 1.478471   
11          0.130734         -0.932632        ...                -0.592312   
12         -0.274731         -1.844704        ...                -0.130967   

    TTGCGTCGTGACTCAT  GAAACTCTCGTGTAGT  GACGCGTGTAGAAAGG  AGCGTCGTCCCAAGTA  \
0           2.131055         -0.928347         -0.444384         -0.624586   
1           2.174037         -0.928347          1.005627         -0.825257   
2          -0.920247         -0.522882          0.076913         -1.348505   
3           4.075033          4.931014          1.302525          4.551563   
4          -1.074398         -0.174575         -0.297780          0.827666   
5          -1.767545         -0.928347         -0.253328          0.902787   
6          -0.786716         -1.216029         -1.191598         -0.537575   
7          -1.479863         -1.398351          1.758672         -0.510176   
8           0.810143          0.083254          1.963036         -0.314432   
9          -0.423811          1.617184    

In [67]:
X = data_adtclr.iloc[:,1:].values
X

array([[ 0.0035229 , -0.1782644 , -1.64752394, ..., -0.58425305,
        -0.90225009, -0.67777809],
       [-0.24009918, -0.64257001, -0.12123328, ..., -0.0203176 ,
         0.91303988,  0.32774377],
       [-0.05204695,  0.00405716,  1.60161701, ..., -0.05540892,
        -0.65093566, -0.49545654],
       ..., 
       [-0.38851918,  1.70880525, -1.51635382, ..., -0.64677341,
        -1.74954795, -0.90092164],
       [-0.24009918, -0.51473663, -0.78380409, ..., -0.58425305,
        -0.90225009, -0.01853246],
       [-0.38851918, -0.40140795, -2.08308708, ..., -0.09177656,
        -0.28321088, -0.90092164]])

In [68]:
Xtrans = np.transpose(X)
Xtrans.shape

(8005, 13)

In [69]:
from sklearn.cluster import KMeans

kmeans_instance = KMeans(n_clusters=10, random_state=2017, n_jobs=8).fit(Xtrans)


In [70]:
y = kmeans_instance.labels_

In [71]:
#cluster counts (8005 total cells)
np.unique(y, return_counts=True)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32),
 array([1959,  271,  526,  337,  386, 2124,  498, 1181,  511,  212]))

In [72]:
y.shape

(8005,)

In [73]:
#1d array to 2d array (so savetxt will write properly)
y = np.reshape(y,(-1,1))
np.transpose(y)

array([[1, 1, 2, ..., 5, 5, 5]], dtype=int32)

In [74]:
#8005 columns, 1 row
#10 clusters are integer values from 0 to 9
np.savetxt("kmeans_10clusters_ADTclr_filtered.csv", np.transpose(y), delimiter=',', fmt='%i')

## do the same for RNA

In [75]:
data_rna = pd.read_csv("./filtered/CBMC_rna_filtered.csv")
data_rna

Unnamed: 0  TACAGTGTCTCGGACG  GTTTCTACATCATCCC  \
0              HUMAN_A1BG                 0                 0   
1          HUMAN_A1BG-AS1                 0                 0   
2               HUMAN_A2M                 0                 0   
3           HUMAN_A2M-AS1                 0                 0   
4            HUMAN_A4GALT                 3                 0   
5              HUMAN_AAAS                 2                 1   
6              HUMAN_AACS                 0                 0   
7             HUMAN_AAED1                 0                 2   
8             HUMAN_AAGAB                 5                 1   
9              HUMAN_AAK1                 0                 0   
10            HUMAN_AAMDC                 1                 2   
11             HUMAN_AAMP                 6                 2   
12             HUMAN_AAR2                 1                 1   
13             HUMAN_AARS                 1                 2   
14            HUMAN_AARS2                 0                 0   
15           HUMAN_AARSD1                 0                 0   
16            HUMAN_AASDH                 1                 0   
17         HUMAN_AASDHPPT                 1                 1   
18             HUMAN_AASS                 0                 0   
19             HUMAN_AATF                 1                 1   
20             HUMAN_AATK                 0                 0   
21             HUMAN_ABAT                 0                 0   
22            HUMAN_ABCA1                 0                 0   
23           HUMAN_ABCA13                 0                 0   
24            HUMAN_ABCA2                 0                 0   
25            HUMAN_ABCA3                 0                 0   
26            HUMAN_ABCA5                 0                 0   
27            HUMAN_ABCA6                 0                 0   
28            HUMAN_ABCA7                 0                 0   
29            HUMAN_ABCA9                 0                 0   
...                   ...               ...               ...   
16279       HUMAN_ZSCAN25                 0                 0   
16280       HUMAN_ZSCAN29                 0                 0   
16281       HUMAN_ZSCAN30                 0                 0   
16282       HUMAN_ZSCAN31                 1                 0   
16283       HUMAN_ZSCAN32                 0                 0   
16284       HUMAN_ZSCAN5A                 0                 0   
16285        HUMAN_ZSCAN9                 0                 0   
16286        HUMAN_ZSWIM1                 0                 0   
16287        HUMAN_ZSWIM3                 0                 0   
16288        HUMAN_ZSWIM4                 0                 0   
16289        HUMAN_ZSWIM6                 0                 0   
16290        HUMAN_ZSWIM7                 1                 2   
16291        HUMAN_ZSWIM8                 0                 0   
16292         HUMAN_ZUFSP                 1                 0   
16293          HUMAN_ZW10                 0                 1   
16294        HUMAN_ZWILCH                 0                 0   
16295         HUMAN_ZWINT                 7                 2   
16296          HUMAN_ZXDA                 0                 1   
16297          HUMAN_ZXDB                 0                 0   
16298          HUMAN_ZXDC                 0                 1   
16299        HUMAN_ZYG11B                 0                 1   
16300           HUMAN_ZYX                 0                 2   
16301         HUMAN_ZZEF1                 0                 1   
16302          HUMAN_ZZZ3                 0                 0   
16303  HUMAN_hsa-mir-1199                 0                 0   
16304   HUMAN_hsa-mir-335                 0                 0   
16305   HUMAN_hsa-mir-490                 0                 0   
16306  HUMAN_hsa-mir-5195                 0                 0   
16307  HUMAN_hsa-mir-6080                 0                 0   
16308  HUMAN_hsa-mir-8072                 0       

In [76]:
X = data_rna.iloc[:,1:].values
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ..., 
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [77]:
Xtrans = np.transpose(X)
Xtrans.shape

(8005, 16309)

In [78]:
from sklearn.cluster import KMeans

kmeans_instance = KMeans(n_clusters=10, random_state=2017, n_jobs=8).fit(Xtrans)


In [79]:
y = kmeans_instance.labels_

In [80]:
#cluster counts (8005 total cells)
np.unique(y, return_counts=True)

### WARNING: don't compare cluster numbers/labels because each run could be different... need other information to match up corresponding

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32),
 array([2055,   31,    5,    6, 3494,  673, 1563,   15,   18,  145]))

In [81]:
y.shape

(8005,)

In [82]:
#1d array to 2d array (so savetxt will write properly)
y = np.reshape(y,(-1,1))
np.transpose(y)

array([[1, 9, 9, ..., 0, 0, 0]], dtype=int32)

In [83]:
#8005 columns, 1 row
#10 clusters are integer values from 0 to 9
np.savetxt("kmeans_10clusters_rna_filtered.csv", np.transpose(y), delimiter=',', fmt='%i')